services:
  alyx_gunicorn:
    image: internationalbrainlab/alyx_apache:latest
    container_name: ibl_alyx_apache
    ports:
      - "8080:8000"
    env_file: .env
    command: >
      bash -c "python /var/www/alyx/alyx/manage.py collectstatic --noinput &&
               gunicorn --workers 2 -b 0.0.0.0:8000 alyx.gunicorn_wsgi:application"
    restart: always
    volumes:
      # - /etc/letsencrypt:/etc/apache2/ssl
      - /var/log/apache2:/var/log/apache2
      - ./settings.py:/var/www/alyx/alyx/alyx/settings.py
    depends_on:
      - postgres
  postgres:
    image: postgres:17
    container_name: ucl_alyx_postgres
    env_file: .env
    volumes:
      - ucl_alyx_postgres:/var/lib/postgresql/data
    expose:
      - 5433
volumes:
  ucl_alyx_postgres: